name: Build, and publish spec to GitHub Pages and /TR/

on:
  pull_request: {}
  push:
    branches: [main]
    paths:
      - 'images/**'
      - 'index.bs'

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: index.bs
          DESTINATION: index.html
          GH_PAGES_BRANCH: gh-pages

# not set 'warning' to BUILD_FAIL_ON (not to cause error by bikeshed warning?)

